In [306]:
import pandas as pd
from datetime import datetime
import numpy as np
from datetime import date
import shutil
import random

In [2]:
df = pd.read_csv('trips.csv')

In [304]:
# 1
def drop_duplicated(df):
    # Trips with similar origin, destination, and time of day should be grouped together.
    data_drop_duplicated = df.drop_duplicates(subset = ["origin_coord", "destination_coord", "datetime"])
    return data_drop_duplicated


# 2
def convert_datetime_type(df):
    df['datetime'] = pd.to_datetime(df['datetime'])
    return df


# 3
def remove_characters(df):
    df['origin_coord'] = df['origin_coord'].str.replace('POINT \(', '', regex=True)
    df['origin_coord'] = df['origin_coord'].str.replace('\)', '', regex=True)
    df['destination_coord'] = df['destination_coord'].str.replace('POINT \(', '', regex=True)
    df['destination_coord'] = df['destination_coord'].str.replace('\)', '', regex=True)
    return df


# 4
def create_long_lat(df):
    df[['lat_origin', 'long_origin']] = df['origin_coord'].str.split(' ', 1, expand=True)
    df[['lat_destination', 'long_destination']] = df['destination_coord'].str.split(' ', 1, expand=True)
    return df


# 5
def remove_excedent_columns(df):
    df = df.drop(labels=['origin_coord', 'destination_coord'], axis=1)
    return df


# 6
def create_week_of_year_by_area(df):
    # Develop a way to obtain the weekly average number of trips for an area, defined by a bounding box (given by coordinates) or by a region.
    trips_by_area = df.groupby(["region", "weekofyear"]).size().reset_index(name='count')
    return trips_by_area

In [ ]:
data_transformed = drop_duplicated(df)
data_transformed

In [ ]:
data_transformed = drop_duplicated(df)
data_transformed = convert_datetime_type(data_transformed)
data_transformed = remove_characters(data_transformed)
data_transformed = create_long_lat(data_transformed)
data_transformed = remove_excedent_columns(data_transformed)
data_transformed

In [ ]:
trips_by_area = create_week_of_year_by_area(data_transformed)
trips_by_area

---

In [203]:
region = ["Hamburg", "Prague", "Turin"]
datetime = [
     '2018-05-01 05:24:37',
     '2018-05-01 10:22:59',
     '2018-05-01 11:50:58',
     '2018-05-01 17:42:05',
     '2018-05-02 00:22:18',
     '2018-05-02 13:48:30',
     '2018-05-03 01:35:44',
     '2018-05-03 05:24:26',
     '2018-05-03 10:45:23',
     '2018-05-03 15:15:28',
     '2018-05-03 16:16:46',
     '2018-05-03 18:56:45',
     '2018-05-04 00:46:12',
     '2018-05-04 02:42:32',
     '2018-05-04 04:40:35',
     '2018-05-05 06:08:53',
     '2018-05-05 07:05:01',
     '2018-05-05 12:39:21',
     '2018-05-06 00:00:44',
     '2018-05-06 05:13:16',
     '2018-05-06 06:34:22',
     '2018-05-06 09:49:16',
     '2018-05-06 12:56:14',
     '2018-05-07 10:28:04',
     '2018-05-08 04:22:01',
     '2018-05-08 04:29:25',
     '2018-05-08 15:11:01',
     '2018-05-09 04:23:26',
     '2018-05-09 09:28:24',
     '2018-05-10 03:37:56',
     '2018-05-10 09:38:12',
     '2018-05-10 17:51:38',
     '2018-05-10 23:04:58',
     '2018-05-11 05:58:34',
     '2018-05-11 21:16:54',
     '2018-05-12 08:13:09',
     '2018-05-12 15:12:04',
     '2018-05-12 16:40:40',
     '2018-05-13 08:52:25',
     '2018-05-13 12:00:21',
     '2018-05-13 13:09:19',
     '2018-05-13 15:37:37',
     '2018-05-13 22:16:27',
     '2018-05-14 01:47:52',
     '2018-05-14 02:07:30',
     '2018-05-14 23:16:56',
     '2018-05-15 06:42:05',
     '2018-05-15 09:13:36',
     '2018-05-15 20:30:12',
     '2018-05-15 22:10:03',
     '2018-05-16 11:56:33',
     '2018-05-17 04:27:09',
     '2018-05-17 20:15:45',
     '2018-05-18 11:07:29',
     '2018-05-18 19:29:56',
     '2018-05-19 09:07:17',
     '2018-05-19 18:32:09',
     '2018-05-19 23:08:09',
     '2018-05-20 01:41:36',
     '2018-05-20 02:31:22',
     '2018-05-20 05:39:56',
     '2018-05-20 05:47:02',
     '2018-05-21 02:54:04',
     '2018-05-21 04:06:11',
     '2018-05-21 06:52:19',
     '2018-05-21 15:36:26',
     '2018-05-21 19:13:24',
     '2018-05-21 20:53:22',
     '2018-05-21 21:32:17',
     '2018-05-22 10:39:49',
     '2018-05-23 01:07:33',
     '2018-05-23 02:18:33',
     '2018-05-23 05:55:37',
     '2018-05-23 08:59:29',
     '2018-05-23 12:43:17',
     '2018-05-23 12:45:54',
     '2018-05-24 18:32:22',
     '2018-05-25 09:59:33',
     '2018-05-25 15:16:35',
     '2018-05-26 01:13:35',
     '2018-05-26 04:25:56',
     '2018-05-26 05:15:45',
     '2018-05-26 06:04:17',
     '2018-05-26 12:14:42',
     '2018-05-26 20:39:37',
     '2018-05-27 07:06:44',
     '2018-05-27 09:49:16',
     '2018-05-27 17:41:17',
     '2018-05-28 04:23:42',
     '2018-05-28 09:03:40',
     '2018-05-28 22:04:56',
     '2018-05-29 03:33:44',
     '2018-05-29 06:06:38',
     '2018-05-29 07:02:25',
     '2018-05-29 12:44:02',
     '2018-05-29 13:42:34',
     '2018-05-29 15:58:39',
     '2018-05-31 06:20:59',
     '2018-05-31 10:55:12',
     '2018-05-31 11:59:33'
    ]
datasource = ['baba_car', 'bad_diesel_vehicles', 'cheap_mobile', 'funny_car', 'pt_search_app']
origin_coord = [
     'POINT (10.00384920850646 53.65220121071665)',
     'POINT (10.02610136178745 53.50122432388112)',
     'POINT (10.03381912541321 53.52487206530561)',
     'POINT (10.04884628340258 53.51430547831718)',
     'POINT (10.05260098579818 53.53497739746809)',
     'POINT (10.06118280297654 53.46738240063593)',
     'POINT (10.07299025213017 53.62044974829032)',
     'POINT (10.0778786538811 53.60371774249091)',
     'POINT (10.08064772413434 53.5438877700869)',
     'POINT (10.08338857045871 53.59661344302611)',
     'POINT (10.1457401708168 53.43686908113324)',
     'POINT (10.15410920623684 53.53092417407957)',
     'POINT (10.17378993097742 53.5467336774148)',
     'POINT (10.17801484401512 53.55155909331071)',
     'POINT (10.19019363228404 53.45209827865287)',
     'POINT (10.20044161946335 53.54722485790852)',
     'POINT (10.20093686911824 53.50775292606026)',
     'POINT (10.2154964127794 53.53161090271701)',
     'POINT (14.31840390580184 50.08466755143189)',
     'POINT (14.32427345662177 50.00002074358429)',
     'POINT (14.33107209002501 50.06307196908211)',
     'POINT (14.33562319852013 50.05977285737693)',
     'POINT (14.34394689715277 50.12299688052901)',
     'POINT (14.34611560109357 50.02251748571683)',
     'POINT (14.34989439101649 50.0578756416996)',
     'POINT (14.35146190337486 50.10386689948413)',
     'POINT (14.37153748521014 50.00937333429672)',
     'POINT (14.37338615486802 50.06537556739956)',
     'POINT (14.37987779362806 50.02580819336156)',
     'POINT (14.38418951543671 50.07570422895751)',
     'POINT (14.40975521275597 50.037791514028)',
     'POINT (14.41986637983827 50.02012470664376)',
     'POINT (14.42318361059361 50.11958193109052)',
     'POINT (14.42406040824624 50.07214185487351)',
     'POINT (14.4251434102725 50.08626745067269)',
     'POINT (14.42559620999022 50.05308939656821)',
     'POINT (14.47912398994219 50.11781434726048)',
     'POINT (14.49290671173996 50.01644032542101)',
     'POINT (14.49581069715323 50.07207927074405)',
     'POINT (14.4973794438195 50.00136875782316)',
     'POINT (14.52723245789148 50.01620449831963)',
     'POINT (14.53300650375239 50.12502233477432)',
     'POINT (14.55782768207913 50.08426714850849)',
     'POINT (14.56801740803507 49.98980557466577)',
     'POINT (14.56861581242726 50.10620152153201)',
     'POINT (14.59545724636152 50.0524554235424)',
     'POINT (14.61738744026195 50.03346482370401)',
     'POINT (14.62777653398497 50.00367807685823)',
     'POINT (14.64292585196625 50.02034172465275)',
     'POINT (14.65754935346634 50.11820315220623)',
     'POINT (14.65848565403607 50.11571340810843)',
     'POINT (14.66689257396927 50.07203997731474)',
     'POINT (7.513135087952872 45.04417775442011)',
     'POINT (7.535738586259044 45.09228283767607)',
     'POINT (7.541509189114433 45.09160503827746)',
     'POINT (7.546386797113857 45.08746266421812)',
     'POINT (7.551997743457845 44.99638623936507)',
     'POINT (7.555153646171233 44.99912435872375)',
     'POINT (7.557295325138827 44.980984165477)',
     'POINT (7.55733220251515 45.04346691930719)',
     'POINT (7.557756740222061 45.0225802162822)',
     'POINT (7.558864701837288 45.11540031667295)',
     'POINT (7.560785081962462 45.01901608530191)',
     'POINT (7.56304564848932 44.97612466562052)',
     'POINT (7.563475091132667 44.97997955620617)',
     'POINT (7.579174066609555 45.07058209228659)',
     'POINT (7.579546999972512 45.07031923406972)',
     'POINT (7.592730702551875 45.10999018294942)',
     'POINT (7.603105215841434 45.0574978503937)',
     'POINT (7.614078119815749 45.13433106465422)',
     'POINT (7.616964015642722 45.04912350611652)',
     'POINT (7.621866502979116 45.08793552379486)',
     'POINT (7.625041142160284 44.98182259298021)',
     'POINT (7.631911234917911 45.07638462112543)',
     'POINT (7.647498943910875 45.01930299183481)',
     'POINT (7.6523523241688 45.13930102848315)',
     'POINT (7.662608916626361 45.09442558983316)',
     'POINT (7.671077441892763 45.00676340143624)',
     'POINT (7.672837913286881 44.9957109242058)',
     'POINT (7.675234513598563 45.08658289542927)',
     'POINT (7.676692231736426 45.06249909939103)',
     'POINT (7.685899281076795 45.07566566332665)',
     'POINT (7.688747565021865 44.98886727473593)',
     'POINT (7.691232870035057 45.06910822622201)',
     'POINT (7.702418079996892 45.05754972796922)',
     'POINT (7.703220872633631 45.12041666625482)',
     'POINT (7.72037765675129 45.1044438436921)',
     'POINT (7.723807753167536 45.02971128289503)',
     'POINT (7.732828486976612 45.09748898017552)',
     'POINT (7.739660019780326 45.10100884469237)',
     'POINT (9.80304883152659 53.50847122244616)',
     'POINT (9.840595540189936 53.50991873196815)',
     'POINT (9.851542240435057 53.49993939960235)',
     'POINT (9.855285083390802 53.49609983095765)',
     'POINT (9.910278201788232 53.58386264717827)',
     'POINT (9.91347867604199 53.64940529138455)',
     'POINT (9.915740323664213 53.60938698922035)',
     'POINT (9.936476031944927 53.45543416459435)',
     'POINT (9.961144659266848 53.42865933587807)',
     'POINT (9.996714798980491 53.52203690589671)'
    ]
destination_coord = [
     'POINT (10.02557919725378 53.4120717767391)',
     'POINT (10.03250822637649 53.50058121032057)',
     'POINT (10.03327373452912 53.65419620043016)',
     'POINT (10.03920714083507 53.56698314675397)',
     'POINT (10.04091186185177 53.42024644236509)',
     'POINT (10.05889649564977 53.49486429314853)',
     'POINT (10.08503581364391 53.43645004358303)',
     'POINT (10.0999398824815 53.55965167658809)',
     'POINT (10.1041201879328 53.42920211427293)',
     'POINT (10.12399795075635 53.62949412099623)',
     'POINT (10.17431393081631 53.51796499041119)',
     'POINT (10.17687554971065 53.63421553339072)',
     'POINT (10.17914017806172 53.60909301795856)',
     'POINT (10.19421502623748 53.49444402955017)',
     'POINT (10.20354128171305 53.51109692120344)',
     'POINT (10.20544652088819 53.5064112329052)',
     'POINT (10.21529787231755 53.50485266884467)',
     'POINT (14.31199296863995 50.09604608872181)',
     'POINT (14.31657321025762 50.09295527259866)',
     'POINT (14.31831785619946 49.999311030748)',
     'POINT (14.3200468695536 50.10807754182695)',
     'POINT (14.34790601885638 50.11666616118271)',
     'POINT (14.3588281620048 50.00428816034508)',
     'POINT (14.40585085170846 50.09331773424552)',
     'POINT (14.41014860957387 50.08518970681641)',
     'POINT (14.41150237340828 50.02800588921088)',
     'POINT (14.43109483523328 50.04052930943246)',
     'POINT (14.44097861083801 49.99269705719384)',
     'POINT (14.45046952210687 50.10077692162883)',
     'POINT (14.45281481537168 50.03751904953268)',
     'POINT (14.45302412886982 50.06961029075634)',
     'POINT (14.47767895969969 50.09339790740321)',
     'POINT (14.48321912885263 50.06509529578676)',
     'POINT (14.48378121129139 50.09770540993485)',
     'POINT (14.48735724430722 50.0275445326544)',
     'POINT (14.49475583828166 50.02232490084747)',
     'POINT (14.5017970263999 50.03963869865565)',
     'POINT (14.54081985518606 50.08790619445585)',
     'POINT (14.54762887318999 50.00573858824717)',
     'POINT (14.54894833778109 50.01480664304733)',
     'POINT (14.54926715156042 50.04365439736826)',
     'POINT (14.55762488630385 50.08502385365859)',
     'POINT (14.59895464921585 50.05472087955579)',
     'POINT (14.60224344606894 50.10794700670115)',
     'POINT (14.60544806001137 50.1174974586993)',
     'POINT (14.61296534823862 50.06347771442317)',
     'POINT (14.64297252209033 50.0121919035355)',
     'POINT (14.65648496061339 50.1233558262903)',
     'POINT (14.6610239449707 50.07877245872595)',
     'POINT (14.66530238921314 50.11783538584734)',
     'POINT (14.66560032530535 50.0869602482622)',
     'POINT (7.517129937471816 45.06482486034779)',
     'POINT (7.526357497337862 44.98174478195055)',
     'POINT (7.527497142312585 45.03335051325654)',
     'POINT (7.531353488607957 45.01346936150077)',
     'POINT (7.546186195389519 45.00660293197863)',
     'POINT (7.555944481215518 44.9974979951791)',
     'POINT (7.558481292621633 45.09629278672146)',
     'POINT (7.579705278243088 45.1042591460774)',
     'POINT (7.583568695710608 45.10526898076209)',
     'POINT (7.586779246260459 45.01495013918306)',
     'POINT (7.592874526101529 45.0395824302331)',
     'POINT (7.597114891145975 45.1162369066238)',
     'POINT (7.613484349321846 45.06088494858106)',
     'POINT (7.623229346744799 44.99969774086024)',
     'POINT (7.631498786757075 45.12355143687468)',
     'POINT (7.634488648561684 45.09941960292201)',
     'POINT (7.639578002290701 45.10020564825853)',
     'POINT (7.643592218026432 45.02125136819493)',
     'POINT (7.66250749081722 45.06472681372993)',
     'POINT (7.673694614207704 45.05708350682146)',
     'POINT (7.686960868773017 45.09709631077637)',
     'POINT (7.695048310476258 45.12827648115218)',
     'POINT (7.698742357182772 45.05242942915245)',
     'POINT (7.700324102531206 45.0688897670161)',
     'POINT (7.703621918783042 45.12162242437576)',
     'POINT (7.713229884381637 45.08729268877508)',
     'POINT (7.714926530712359 45.0772550203861)',
     'POINT (7.715597191909829 45.05465181263087)',
     'POINT (7.7199332961156 44.98171705467543)',
     'POINT (7.720368637535126 45.06782385393849)',
     'POINT (7.724289698249433 45.07378523979249)',
     'POINT (7.731930611357271 45.07122576386962)',
     'POINT (7.738953769704938 45.03730563222917)',
     'POINT (7.74528653441973 45.02628598341506)',
     'POINT (7.761744775147509 44.98665501392073)',
     'POINT (7.763266287022981 45.03194358259004)',
     'POINT (7.770328470181719 45.05433872971169)',
     'POINT (7.776838688899015 45.02291834470744)',
     'POINT (9.789197601249002 53.46315765148751)',
     'POINT (9.805977128944804 53.56924626552725)',
     'POINT (9.822644521723184 53.60047266825603)',
     'POINT (9.834147669301471 53.6513082275632)',
     'POINT (9.834883820942993 53.63694321201706)',
     'POINT (9.836133816394081 53.5340991521548)',
     'POINT (9.857518857977054 53.52506880668962)',
     'POINT (9.880352497673615 53.56088794736056)',
     'POINT (9.944925737232104 53.42494618904695)',
     'POINT (9.958672518621771 53.5509263400788)',
     'POINT (9.985427968556252 53.41711096758155)'
    ]

In [3]:
df.columns

Index(['region', 'origin_coord', 'destination_coord', 'datetime',
       'datasource'],
      dtype='object')

In [243]:
million_df = pd.DataFrame(columns = [
    'region',
    'origin_coord',
    'destination_coord',
    'datetime',
    'datasource'
])

In [245]:
# Create data with new values
for i in range(0, 100000000):
    region_data = random.choice(region)
    origin_coord_data = random.choice(origin_coord)
    destination_coord_data = random.choice(destination_coord)
    datetime_data = random.choice(datetime)
    datasource_data = random.choice(datasource)
    data_to_append = pd.DataFrame(
        {
            "region": [region_data],
            "origin_coord": [origin_coord_data],
            "destination_coord": [destination_coord_data],
            "datetime": [datetime_data],
            "datasource": [datasource_data]
        }
    )
    million_df = million_df.append(data_to_append)

million_df.to_csv("million.csv")

KeyboardInterrupt

In [244]:
million_df

Empty DataFrame
Columns: [region, origin_coord, destination_coord, datetime, datasource]
Index: []

In [175]:
# Develop a way to inform the user about the status of the data ingestion without using a polling solution.
using Slack channel

SyntaxError: invalid syntax (3126521007.py, line 2)

In [ ]:
# The solution should be scalable to 100 million entries.
# It is encouraged to simplify the data by a data model.
# Please add proof that the solution is scalable.
# Mock data to create more lines, run file by chunks

In [ ]:
# Use a SQL database
Use SQL to save those informations

In [250]:
import os

In [256]:
def get_file_names(files_path, folder_name):
    """Get all file names that would be loaded, from specific folder and specific path.

    Args:
        files_path: File path that parquet are stored, to read it on local folders.
        folder_name: Folder name to find files.

    Returns:
        An array with all create tables. For example:
        ["acute_g_day_bw_all_days", "acute_g_day_bw_cons_days", "chronic_g_day_bw_to_t_pop", ...]
    """
    files_name = None
    for root, directories, files in os.walk(files_path):
        if folder_name in root:
            files_name = files
    files_name_regexp = [ name.replace(".sql", "") for name in files_name]
    return files_name_regexp

In [257]:
get_file_names('Untitled Folder/', 'create_table')

['trips-Copy1.csv']

In [262]:
import pprint

In [268]:
def load_chunk_data(df) -> pd.DataFrame:
#     file_path = kwargs.get("file_path")
#     file_name = kwargs.get("file_name")
    chunk_size = kwargs.get("chunk_size", 10000)
    df = pd.read_csv(df, chunksize=chunk_size)

In [274]:
chunk = 10000
# pd.read_csv("big_trips.csv", chunksize=10000)

In [275]:
pd_df = pd.concat(chunk)
pd_df

,region,origin_coord,destination_coord,datetime,datasource
0,Turin,POINT (14.42318361059361 50.11958193109052),POINT (7.761744775147509 44.98665501392073),2018-05-09 04:23:26,pt_search_app
1,Prague,POINT (7.616964015642722 45.04912350611652),POINT (7.74528653441973 45.02628598341506),2018-05-15 09:13:36,funny_car
2,Prague,POINT (7.603105215841434 45.0574978503937),POINT (10.17431393081631 53.51796499041119),2018-05-18 11:07:29,cheap_mobile
3,Prague,POINT (14.38418951543671 50.07570422895751),POINT (7.7199332961156 44.98171705467543),2018-05-03 01:35:44,funny_car
4,Hamburg,POINT (7.672837913286881 44.9957109242058),POINT (14.64297252209033 50.0121919035355),2018-05-05 07:05:01,pt_search_app
...,...,...,...,...,...
99995,Hamburg,POINT (7.732828486976612 45.09748898017552),POINT (9.834883820942993 53.63694321201706),2018-05-03 18:56:45,cheap_mobile
99996,Hamburg,POINT (7.555153646171233 44.99912435872375),POINT (9.958672518621771 53.5509263400788),2018-05-17 04:27:09,cheap_mobile
99997,Turin,POINT (7.535738586259044 45.09228283767607),POINT (7.7199332961156 44.98171705467543),2018-05-26 04:25:56,pt_search_app
99998,Hamburg,POINT (9.80304883152659 53.50847122244616),POINT (7.770328470181719 45.05433872971169),2018-05-08 04:29:25,pt_search_app
99999,Prague,POINT (7.702418079996892 45.05754972796922),POINT (10.20354128171305 53.51109692120344),2018-05-21 19:13:24,baba_car

In [310]:
def load_chunk_data(file_path, file_name, chunk_size):
    now = datetime.now()
    date_time = now.strftime("%m_%d_%Y")
    df = pd.read_csv(f"{file_path}/{file_name}", chunksize=chunk_size)
    src_path = f"{file_path}/{file_name}"
    dst_path = f"{file_path}/../done/{file_name}"
    part = 0
    for chunk in df:
        df_drop_duplicated = drop_duplicated(chunk)
        df_convert_datetime = convert_datetime_type(df_drop_duplicated)
        df_remove_characters = remove_characters(df_convert_datetime)
        df_create_long_lat = create_long_lat(df_remove_characters)
        df_remove_excedent_columns = remove_excedent_columns(df_create_long_lat)
        df_remove_excedent_columns.to_csv(f"{file_path}/chunks/{file_name}_{date_time}_{part}")
        part+=1
    shutil.move(src_path, dst_path)

In [312]:
file_path = "./files/consume/"
file_name = "trips.csv"
chunk_size = 10
load_chunk_data(file_path, file_name, chunk_size)

---